/**
 * Type definitions for the lending platform
 *
 * Note: In production, these would be generated by `daml codegen js`
 * For now, we define them manually to match the DAML contracts
 */

// Re-export generated types when available
// export * from '../../daml.js/canton-lending';

// Manual type definitions (until codegen runs)

export type LoanStatus = 'Proposed' | 'Funded' | 'Repaid' | 'Closed' | 'Rejected';

export interface LoanRequest {
  borrower: string;
  lender: string;
  asset: string;
  principal: string;
  interestRate: string;
  termDays: string;
  requestDate: string;
}

export interface Loan {
  borrower: string;
  lender: string;
  asset: string;
  principal: string;
  interest: string;
  startDate: string;
  dueDate: string;
  status: LoanStatus;
}

export interface ContractInfo<T> {
  contractId: string;
  payload: T;
}
